# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/electricwiz/geant4/RICH

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/electricwiz/geant4/RICH/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/electricwiz/geant4/RICH/build/CMakeFiles /home/electricwiz/geant4/RICH/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/electricwiz/geant4/RICH/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sim

# Build rule for target.
sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sim
.PHONY : sim

# fast build rule for target.
sim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/build
.PHONY : sim/fast

#=============================================================================
# Target rules for targets named Simulation

# Build rule for target.
Simulation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Simulation
.PHONY : Simulation

# fast build rule for target.
Simulation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Simulation.dir/build.make CMakeFiles/Simulation.dir/build
.PHONY : Simulation/fast

Action.o: Action.cc.o
.PHONY : Action.o

# target to build an object file
Action.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Action.cc.o
.PHONY : Action.cc.o

Action.i: Action.cc.i
.PHONY : Action.i

# target to preprocess a source file
Action.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Action.cc.i
.PHONY : Action.cc.i

Action.s: Action.cc.s
.PHONY : Action.s

# target to generate assembly for a file
Action.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Action.cc.s
.PHONY : Action.cc.s

Construction.o: Construction.cc.o
.PHONY : Construction.o

# target to build an object file
Construction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Construction.cc.o
.PHONY : Construction.cc.o

Construction.i: Construction.cc.i
.PHONY : Construction.i

# target to preprocess a source file
Construction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Construction.cc.i
.PHONY : Construction.cc.i

Construction.s: Construction.cc.s
.PHONY : Construction.s

# target to generate assembly for a file
Construction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Construction.cc.s
.PHONY : Construction.cc.s

Detector.o: Detector.cc.o
.PHONY : Detector.o

# target to build an object file
Detector.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Detector.cc.o
.PHONY : Detector.cc.o

Detector.i: Detector.cc.i
.PHONY : Detector.i

# target to preprocess a source file
Detector.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Detector.cc.i
.PHONY : Detector.cc.i

Detector.s: Detector.cc.s
.PHONY : Detector.s

# target to generate assembly for a file
Detector.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Detector.cc.s
.PHONY : Detector.cc.s

EventAction.o: EventAction.cc.o
.PHONY : EventAction.o

# target to build an object file
EventAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/EventAction.cc.o
.PHONY : EventAction.cc.o

EventAction.i: EventAction.cc.i
.PHONY : EventAction.i

# target to preprocess a source file
EventAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/EventAction.cc.i
.PHONY : EventAction.cc.i

EventAction.s: EventAction.cc.s
.PHONY : EventAction.s

# target to generate assembly for a file
EventAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/EventAction.cc.s
.PHONY : EventAction.cc.s

Generator.o: Generator.cc.o
.PHONY : Generator.o

# target to build an object file
Generator.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Generator.cc.o
.PHONY : Generator.cc.o

Generator.i: Generator.cc.i
.PHONY : Generator.i

# target to preprocess a source file
Generator.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Generator.cc.i
.PHONY : Generator.cc.i

Generator.s: Generator.cc.s
.PHONY : Generator.s

# target to generate assembly for a file
Generator.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Generator.cc.s
.PHONY : Generator.cc.s

Run.o: Run.cc.o
.PHONY : Run.o

# target to build an object file
Run.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Run.cc.o
.PHONY : Run.cc.o

Run.i: Run.cc.i
.PHONY : Run.i

# target to preprocess a source file
Run.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Run.cc.i
.PHONY : Run.cc.i

Run.s: Run.cc.s
.PHONY : Run.s

# target to generate assembly for a file
Run.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Run.cc.s
.PHONY : Run.cc.s

Sim.o: Sim.cc.o
.PHONY : Sim.o

# target to build an object file
Sim.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Sim.cc.o
.PHONY : Sim.cc.o

Sim.i: Sim.cc.i
.PHONY : Sim.i

# target to preprocess a source file
Sim.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Sim.cc.i
.PHONY : Sim.cc.i

Sim.s: Sim.cc.s
.PHONY : Sim.s

# target to generate assembly for a file
Sim.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/Sim.cc.s
.PHONY : Sim.cc.s

SteppingAction.o: SteppingAction.cc.o
.PHONY : SteppingAction.o

# target to build an object file
SteppingAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/SteppingAction.cc.o
.PHONY : SteppingAction.cc.o

SteppingAction.i: SteppingAction.cc.i
.PHONY : SteppingAction.i

# target to preprocess a source file
SteppingAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/SteppingAction.cc.i
.PHONY : SteppingAction.cc.i

SteppingAction.s: SteppingAction.cc.s
.PHONY : SteppingAction.s

# target to generate assembly for a file
SteppingAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/SteppingAction.cc.s
.PHONY : SteppingAction.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Simulation"
	@echo "... sim"
	@echo "... Action.o"
	@echo "... Action.i"
	@echo "... Action.s"
	@echo "... Construction.o"
	@echo "... Construction.i"
	@echo "... Construction.s"
	@echo "... Detector.o"
	@echo "... Detector.i"
	@echo "... Detector.s"
	@echo "... EventAction.o"
	@echo "... EventAction.i"
	@echo "... EventAction.s"
	@echo "... Generator.o"
	@echo "... Generator.i"
	@echo "... Generator.s"
	@echo "... Run.o"
	@echo "... Run.i"
	@echo "... Run.s"
	@echo "... Sim.o"
	@echo "... Sim.i"
	@echo "... Sim.s"
	@echo "... SteppingAction.o"
	@echo "... SteppingAction.i"
	@echo "... SteppingAction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

